# coding: utf-8

class Team():
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, team_level: float=None, players: list[object]=None):  # noqa: E501
        """Team - a model defined in Swagger

        :param team_level: The team_level of this Team.  # noqa: E501
        :type team_level: float
        :param players: The players of this Team.  # noqa: E501
        :type players: List[object]
        """
        self.swagger_types = {
            'team_level': float,
            'players': list[object]
        }

        self.attribute_map = {
            'team_level': 'teamLevel',
            'players': 'players'
        }
        self._team_level = team_level
        self._players = players

    @property
    def team_level(self) -> float:
        """Gets the team_level of this Team.


        :return: The team_level of this Team.
        :rtype: float
        """
        return self._team_level

    @team_level.setter
    def team_level(self, team_level: float):
        """Sets the team_level of this Team.


        :param team_level: The team_level of this Team.
        :type team_level: float
        """

        self._team_level = team_level

    @property
    def players(self) -> list[object]:
        """Gets the players of this Team.


        :return: The players of this Team.
        :rtype: List[object]
        """
        return self._players

    @players.setter
    def players(self, players: list[object]):
        """Sets the players of this Team.


        :param players: The players of this Team.
        :type players: List[object]
        """

        self._players = players
